name: ci

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: false
        default: '0.0.0'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
  style:
    name: Style
    runs-on : ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        
      - name: staticcheck
        run: staticcheck ./...

      - name: Style
        run: go fmt ./...

      - name: test -z
        run: test -z $(go fmt ./...)     

      - name: Run Tests
        run: go test ./... -cover

      - name: Success!!
        run: (exit 0)